// Self-hosted tech logos (public/tech-icons). We used to hotlink cdn.simpleicons.org,
// but Simple Icons periodically removes brands (AWS, Azure, OpenAI, Adobe…), which
// left dozens of broken external images across the site. Logos come from Simple
// Icons or Iconify's "logos" set; re-download into public/tech-icons to add more.
const TECH_ICONS: Record<string, string> = {
  "AWS": "/tech-icons/aws.svg",
  "AWS Mobile": "/tech-icons/awsmobile.svg",
  "AWS S3": "/tech-icons/awss3.svg",
  "Adobe Creative Suite": "/tech-icons/adobecreativesuite.svg",
  "Adobe XD": "/tech-icons/adobexd.svg",
  "Azure": "/tech-icons/azure.svg",
  "BigCommerce": "/tech-icons/bigcommerce.svg",
  "Buffer": "/tech-icons/buffer.svg",
  "CloudWatch": "/tech-icons/cloudwatch.svg",
  "Docker": "/tech-icons/docker.svg",
  "Express.js": "/tech-icons/expressjs.svg",
  "Facebook Ads": "/tech-icons/facebookads.svg",
  "Fastlane": "/tech-icons/fastlane.svg",
  "Figma": "/tech-icons/figma.svg",
  "Firebase": "/tech-icons/firebase.svg",
  "Flutter": "/tech-icons/flutter.svg",
  "Framer": "/tech-icons/framer.svg",
  "GitHub Actions": "/tech-icons/githubactions.svg",
  "Google Ads": "/tech-icons/googleads.svg",
  "Google Analytics": "/tech-icons/googleanalytics.svg",
  "Google Cloud": "/tech-icons/googlecloud.svg",
  "Google Tag Manager": "/tech-icons/googletagmanager.svg",
  "Grafana": "/tech-icons/grafana.svg",
  "GraphQL": "/tech-icons/graphql.svg",
  "Hootsuite": "/tech-icons/hootsuite.svg",
  "Hotjar": "/tech-icons/hotjar.svg",
  "HubSpot": "/tech-icons/hubspot.svg",
  "Illustrator": "/tech-icons/illustrator.svg",
  "InVision": "/tech-icons/invision.svg",
  "Instagram Ads": "/tech-icons/instagramads.svg",
  "Jest": "/tech-icons/jest.svg",
  "Kotlin": "/tech-icons/kotlin.svg",
  "Kubernetes": "/tech-icons/kubernetes.svg",
  "LinkedIn Ads": "/tech-icons/linkedinads.svg",
  "Magento": "/tech-icons/magento.svg",
  "Mailchimp": "/tech-icons/mailchimp.svg",
  "Maze": "/tech-icons/maze.svg",
  "Meta Business Suite": "/tech-icons/metabusinesssuite.svg",
  "MongoDB": "/tech-icons/mongodb.svg",
  "Next.js": "/tech-icons/nextjs.svg",
  "Nginx": "/tech-icons/nginx.svg",
  "Node.js": "/tech-icons/nodejs.svg",
  "OpenAI API": "/tech-icons/openaiapi.svg",
  "PayPal": "/tech-icons/paypal.svg",
  "Photoshop": "/tech-icons/photoshop.svg",
  "PostgreSQL": "/tech-icons/postgresql.svg",
  "Principle": "/tech-icons/principle.svg",
  "Prometheus": "/tech-icons/prometheus.svg",
  "React": "/tech-icons/react.svg",
  "React Native": "/tech-icons/reactnative.svg",
  "Redis": "/tech-icons/redis.svg",
  "SEMrush": "/tech-icons/semrush.svg",
  "Sentry": "/tech-icons/sentry.svg",
  "Shopify": "/tech-icons/shopify.svg",
  "Sketch": "/tech-icons/sketch.svg",
  "Storybook": "/tech-icons/storybook.svg",
  "Stripe": "/tech-icons/stripe.svg",
  "Swift": "/tech-icons/swift.svg",
  "Tailwind CSS": "/tech-icons/tailwindcss.svg",
  "Terraform": "/tech-icons/terraform.svg",
  "TikTok Ads": "/tech-icons/tiktokads.svg",
  "TypeScript": "/tech-icons/typescript.svg",
  "Vercel": "/tech-icons/vercel.svg",
  "WebSockets": "/tech-icons/websockets.svg",
  "WooCommerce": "/tech-icons/woocommerce.svg",
  "Zeplin": "/tech-icons/zeplin.svg",
  "Content CMS": "/tech-icons/contentcms.svg",
  "Inventory APIs": "/tech-icons/inventoryapis.svg",
  "JavaScript": "/tech-icons/javascript.svg",
  "HTML5": "/tech-icons/html5.svg",
  "CSS3": "/tech-icons/css3.svg",
  "Angular": "/tech-icons/angular.svg",
  "Bootstrap": "/tech-icons/bootstrap.svg",
  "Vue.js": "/tech-icons/vuejs.svg",
  "Laravel": "/tech-icons/laravel.svg",
  "PHP": "/tech-icons/php.svg",
  "MySQL": "/tech-icons/mysql.svg",
  "Supabase": "/tech-icons/supabase.svg",
};

/** Local logo URL for a technology name, or null if we don't have one. */
export function getTechIconUrl(techName: string): string | null {
  return TECH_ICONS[techName] ?? null;
}
