import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "../styles/curve.css";

// 👇 import the ScrollProvider, Curve component, and AnimatePresence
import { ScrollProvider } from "../context/ScrollContext";
import Curve from "../components/Curve";
import { AnimatePresence } from 'framer-motion';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 👇 Wrap everything with ScrollProvider and AnimatePresence */}
        <ScrollProvider>
          <AnimatePresence mode="wait">
            <Curve backgroundColor="#ffffff">
              {children}
            </Curve>
          </AnimatePresence>
        </ScrollProvider>
      </body>
    </html>
  );
}
